services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
      PGTZ: ${TZ}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - athena_db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./server/src:/app/src
      - ./athena:/app/athena
      - ./files:/app/files
      - ./database:/app/database
      - ./public:/app/public
    environment:
      - TZ=America/Los_Angeles
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ENABLE_GOOGLE_NOTES=${ENABLE_GOOGLE_NOTES}
      - ENABLE_DB_ADMIN=${ENABLE_DB_ADMIN}
      - SSO_MICROSOFT_CLIENT_ID=${SSO_MICROSOFT_CLIENT_ID}
      - SSO_MICROSOFT_CLIENT_SECRET=${SSO_MICROSOFT_CLIENT_SECRET}
      - SSO_MICROSOFT_TENANT_ID=${SSO_MICROSOFT_TENANT_ID}
      - SSO_GOOGLE_CLIENT_ID=${SSO_GOOGLE_CLIENT_ID}
      - SSO_GOOGLE_CLIENT_SECRET=${SSO_GOOGLE_CLIENT_SECRET}
      - SSO_GITHUB_CLIENT_ID=${SSO_GITHUB_CLIENT_ID}
      - SSO_GITHUB_CLIENT_SECRET=${SSO_GITHUB_CLIENT_SECRET}
      - SSO_LINKEDIN_CLIENT_ID=${SSO_LINKEDIN_CLIENT_ID}
      - SSO_LINKEDIN_CLIENT_SECRET=${SSO_LINKEDIN_CLIENT_SECRET}
      - SSO_TWITTER_CLIENT_ID=${SSO_TWITTER_CLIENT_ID}
      - SSO_TWITTER_CLIENT_SECRET=${SSO_TWITTER_CLIENT_SECRET}
      - SSO_ALLOWED_DOMAINS=${SSO_ALLOWED_DOMAINS}
      - SSO_ALLOWED_EMAILS=${SSO_ALLOWED_EMAILS}
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/athena/api/google_api/key.json
      - TEST_FAILURES_ENABLED=${TEST_FAILURES_ENABLED}
      - TEST_FAILURE_DEVICE_AVAILABILITY=${TEST_FAILURE_DEVICE_AVAILABILITY}
      - TEST_FAILURE_STUDENT_VALIDATION=${TEST_FAILURE_STUDENT_VALIDATION}
      - TEST_FAILURE_DATA_COMPLETENESS=${TEST_FAILURE_DATA_COMPLETENESS}
      - TEST_FAILURE_PROCESSING_CHECKOUT=${TEST_FAILURE_PROCESSING_CHECKOUT}
      - TEST_FAILURE_UPDATING_STATUS=${TEST_FAILURE_UPDATING_STATUS}
      - TEST_FAILURE_EXTERNAL_SYSTEMS=${TEST_FAILURE_EXTERNAL_SYSTEMS}
      - TEST_FAILURE_DATABASE_UPDATES=${TEST_FAILURE_DATABASE_UPDATES}
      - TEST_FAILURE_POST_FLIGHT=${TEST_FAILURE_POST_FLIGHT}
      - HIDE_ORG_FROM_REPORTS=${HIDE_ORG_FROM_REPORTS}
      - AERIES_ENDPOINT=${AERIES_ENDPOINT}
      - AERIES_API_KEY=${AERIES_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  athena:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    #user: "36464:36464"
    volumes:
      - ./src:/app/src
      - ./files:/app/files
    environment:
      - TZ=${TZ}
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  athena_db: {}
